[package]
name = "iptoasn-webservice"
version = "0.2.1"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
clap = "~2"
flate2 = "~0.2"
horrorshow = "~0.6"
hyper = "~0.10"
iron = "~0.5"
log = "~0.3"
router = "~0.5"
serde = "~1.0"
serde_json = "~1.0"
clippy = {version = "~0", optional = true}

[features]
default = []

[profile.release]
lto = true
panic = "abort"
opt-level = 3
